### ISSUE TITLE
cannot import name 'backend'

### ISSUE THREAD

**Issue by karljiang118440** [bubbliiiing/retinaface-keras#1]
Hi,up 主，我在 linux 下运行你的工程提示：

from utils import backend
ImportError: cannot import name 'backend'

请问需要怎么修改吗？

**Comment by bubbliiiing** [comment]
相对目录放好

**Comment by karljiang118440** [comment]
hi，已经搞定了。我在utils 下面新建立了一个 __init__.py 就搞定了，谢谢。
