### ISSUE TITLE
训练时出现的问题

### ISSUE THREAD

**Issue by zhangxujinsh** [bubbliiiing/retinaface-keras#9]
@bubbliiiing   下面的情况不知有无碰到过？
环境：tf1.15   ubuntu16.04
在retinanet_training.py文件的类Generator函数__getitem__下：  img = Image.open(self.imgs_path[i])  出现: IndexError: list index out range.
Error的出现不固定，有时某个epoch不出问题， 有时候在某个index出问题。

**Comment by bubbliiiing** [comment]
解决了嘛，我没遇上过诶

**Comment by zhangxujinsh** [comment]
已经解决。 没有遇到这个问题最好了

**Comment by zhaozhen1002** [comment]
你好, 请问是怎么解决的呀
